In [1]:
##importing the libraries
import pandas as pd
import numpy as np

In [2]:
##reading the dataset
dataset = pd.read_excel('Real estate valuation data set.xlsx')

In [3]:
##showing the dataset
dataset.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.916667,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.916667,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583333,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500000,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833333,5.0,390.56840,5,24.97937,121.54245,43.1

In [4]:
##dataset columns for our convinience
dataset.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [5]:
##droping the first two columns because we dont require that right now 
dataset.drop(['No', 'X1 transaction date'],axis = 1,inplace = True)

In [6]:
dataset.head()

,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,32.0,84.87882,10,24.98298,121.54024,37.9
1,19.5,306.59470,9,24.98034,121.53951,42.2
2,13.3,561.98450,5,24.98746,121.54391,47.3
3,13.3,561.98450,5,24.98746,121.54391,54.8
4,5.0,390.56840,5,24.97937,121.54245,43.1

In [7]:
## altering the dataset because the distance between the expected and real answer looks too uch so to minimize it we are going to take everything in decimal points 
##
dataset['X2 house age'] = dataset['X2 house age']/100
dataset['X3 distance to the nearest MRT station'] = dataset['X3 distance to the nearest MRT station']/1000
dataset['X4 number of convenience stores'] = dataset['X4 number of convenience stores']/10
dataset['X5 latitude'] = dataset['X5 latitude']/100
dataset['X6 longitude'] = dataset['X6 longitude']/1000
dataset['Y house price of unit area'] = dataset['Y house price of unit area']/100

In [8]:
##renaming for my convinienece
dataset['X1'] = dataset['X2 house age']
dataset['X2'] = dataset['X3 distance to the nearest MRT station']
dataset['X3'] = dataset['X4 number of convenience stores']
dataset['X4'] = dataset['X5 latitude']
dataset['X5'] = dataset['X6 longitude']
dataset['Y'] = dataset['Y house price of unit area']
##droping teh columns because we have copy of all the other columns 
dataset.drop(['X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],axis =1 ,inplace = True)

In [9]:
dataset.head()

      X1        X2   X3        X4        X5      Y
0  0.320  0.084879  1.0  0.249830  0.121540  0.379
1  0.195  0.306595  0.9  0.249803  0.121540  0.422
2  0.133  0.561984  0.5  0.249875  0.121544  0.473
3  0.133  0.561984  0.5  0.249875  0.121544  0.548
4  0.050  0.390568  0.5  0.249794  0.121542  0.431

In [10]:
dataset.drop(['Y'],axis =1 ,inplace =True)

In [11]:
dataset.head()

      X1        X2   X3        X4        X5
0  0.320  0.084879  1.0  0.249830  0.121540
1  0.195  0.306595  0.9  0.249803  0.121540
2  0.133  0.561984  0.5  0.249875  0.121544
3  0.133  0.561984  0.5  0.249875  0.121544
4  0.050  0.390568  0.5  0.249794  0.121542

In [12]:
x = dataset.iloc[:,:].values

In [13]:

weights = np.random.uniform(size = (2,1))

In [14]:
weights

array([[0.44209753],
       [0.60171963]])

In [15]:
l = x[0]
l

array([0.32      , 0.08487882, 1.        , 0.2498298 , 0.12154024])

In [16]:
weights[1,0]

0.6017196278495036

In [17]:
first_weights = weights[0,0]
second_weights = weights[1,0]

In [18]:
##getting the learning rate
leanring_rate = np.random.rand()

In [19]:
learning_rate = leanring_rate

In [20]:
## we are going to categories into two clusters so we are just taking two variable and calculate which cluster will belong to which cluster

first_weight = 0.3
second_weight = 0.7

In [21]:
##      ________________ALGORITHM____________________
##      initialize weights
##      try to find which weight is neare to those points (Xi-weights i)^2
##      put that point to \that cluster 
##      update the weights for all the points
##      decrease the topoloogy

##answer list  for the answers 
answer = []
for l in x:
    for i in range(5):
        ##calculate the weights that is which will belong to which cluster 
        first_weight = (l[i] - first_weight)
        second_weight = (l[i]-second_weight)
    ##finding minimun
    if(first_weight>second_weight):
        answer.append(2)
    else:
        answer.append(1)
    print(first_weight,second_weight)
    ##updationg of the weights
    for p in range(5):
        first_weight = first_weight+(learning_rate*(l[p]-first_weight))
        second_weight = second_weight + (learning_rate*(l[i]-second_weight))
    learning_rate = learning_rate*0.05

0.80683162 0.40683161999999995
0.3959635709310802 0.5336328452591039
-0.4476776088878617 -0.5368400416674003
0.3850968433396502 0.47496849684810216
-0.3538915758446518 -0.44366552994483666
-1.5782670760244408 -1.4884922359930477
1.8715352208163476 1.7817608593645966
-1.4843995773360796 -1.3946252073549514
-3.738663346517193 -3.8284377159331178
2.306325105975169 2.396099475504814
-2.3917396859655202 -2.481514055492482
3.136083425964806 3.2258577954917755
-3.126428855964767 -3.2162032254917334
1.132683515964765 1.2224578854917316
-1.8939030559647652 -1.9836774254917318
1.7434169459647655 1.833191315491732
-1.5646445659647652 -1.6544189354917318
1.3625698559647652 1.4523442254917318
-0.8898366459647652 -0.9796110154917318
1.453317625964765 1.5430919954917317
-3.5123145159647655 -3.602088885491732
3.9099345259647658 3.9997088954917324
-5.151045505964766 -5.240819875491733
5.544665515964766 5.634439885491733
-5.357559665964766 -5.447334035491733
4.234454725964767 4.3242290954917335
-4.215581715964768 -4.305356085491734
4.415112545964768 4.504886915491735
-4.508794475964767 -4.598568845491734
4.500341315964767 4.5901156854917335
-8.889018045964766 -8.978792415491732
8.987320625964765 9.07709499549173
-9.125093715964766 -9.214868085491732
9.438197425964765 9.52797179549173
-8.917863895964766 -9.007638265491732
4.848818155964765 4.938592525491731
-6.564951175964764 -6.65472554549173
5.296840195964764 5.38661456549173
-5.371974575964765 -5.46174894549173
5.616372955964764 5.70614732549173
-9.690299645964764 -9.78007401549173
5.6637863659647625 5.753560735491728
-5.450340985964763 -5.540115355491729
5.753222095964763 5.842996465491729
-5.987895145964763 -6.077669515491729
6.536919285964762 6.626693655491728
-6.012040005964763 -6.1018143754917284
5.902081755964763 5.991856125491728
-10.393803375964762 -10.483577745491727
6.1494472959647615 6.239221665491727
-6.173197575964761 -6.262971945491727
4.69980419596476 4.789578565491726
-5.64560759596476 -5.735381965491726
5.658262165964761 5.748036535491726
-5.414863785964761 -5.504638155491727
4.443265075964761 4.533039445491727
-3.806699385964761 -3.896473755491727
4.357187845964761 4.446962215491727
-8.592543925964762 -8.682318295491728
8.76144750596476 8.851221875491728
-10.510776295964762 -10.60055066549173
10.775902255964763 10.86567662549173
-12.607897015964761 -12.697671385491729
12.37222396596476 12.461998335491728
-13.32106071596476 -13.410835085491728
14.27009760596476 14.359871975491728
-13.981798315964761 -14.071572685491729
14.333861485964762 14.42363585549173
-14.022342835964762 -14.11211720549173
13.957027645964763 14.04680201549173
-13.209683905964761 -13.299458275491729
13.095725655964763 13.18550002549173
-12.523489425964762 -12.61326379549173
8.451562735964762 8.54133710549173
-7.891416915964763 -7.981191285491731
6.626305935964762 6.7160803054917295
-6.711940965964762 -6.801715335491729
4.903693135964762 4.993467505491729
-5.002356225964761 -5.092130595491729
3.7395498959647613 3.8293242654917288
-3.8832229459647607 -3.972997315491728
4.2853242859647604 4.375098655491728
-3.73238896596476 -3.8221633354917275
1.4498996759647602 1.5396740454917277
-1.1103090359647603 -1.2000834054917278
1.5431999659647604 1.6329743354917279
-3.0089609659647603 -3.0987353354917277
-1.0165523140352397 -0.9267779445082722
-0.42920740596476037 -0.5189817754917279
-3.4167134640352397 -3.326939094508272
3.11448165403524 3.0247072845082723
-4.55382695403524 -4.464052584508273
2.5620816140352405 2.472307244508273
-3.51737185403524 -3.4275974845082726
4.1306502140352395 4.040875844508272
-3.7835870440352393 -3.6938126745082718
4.52893078403524 4.439156414508273
-4.69061479403524 -4.600840424508273
4.93701317403524 4.847238804508272
-4.191669434035239 -4.101895064508272
3.6735667440352384 3.583792374508272
-3.744902904035238 -3.6551285345082714
4.034202194035238 3.9444278245082716
-3.770616054035238 -3.6808416845082714
4.177072854035238 4.0872984845082705
-3.998300474035238 -3.9085261045082706
4.652554754035238 4.562780384508271
-5.918665734035239 -5.828891364508271
5.711974744035238 5.622200374508271
-7.647467804035239 -7.557693434508272
7.995530974035239 7.905756604508271
-7.287376034035239 -7.197601664508271
5.455859254035238 5.366084884508271
-5.229198934035239 -5.139424564508271
6.063086554035238 5.973312184508271
-6.523264464035237 -6.43349009450827
0.40802279403523684 0.31824842450826935
-4.597256464035237 -4.507482094508269
3.4383893540352366 3.348614984508269
-3.189990974035237 -3.1002166045082693
3.202645544035237 3.1128711745082693
-3.1869909740352367 -3.097216604508269
3.358768114035237 3.2689937445082693
-3.672377014035237 -3.5826026445082695
4.063997024035237 3.97422265450827
-3.7746977340352372 -3.6849233645082697
3.6277590040352368 3.5379846345082693
-3.6018859940352366 -3.512111624508269
4.361767784035236 4.271993414508269
-3.6218676640352365 -3.532093294508269
4.054067994035236 3.964293624508269
-5.989561054035237 -5.899786684508269
6.144598284035237 6.05482391450827
-5.666317164035238 -5.576542794508271
6.2852302740352375 6.19545590450827
-7.233551464035237 -7.14377709450827
7.328731814035237 7.238957444508269
-7.039909344035238 -6.950134974508271
6.069182704035238 5.97940833450827
-6.060528134035237 -5.970753764508269
6.304926514035237 6.215152144508269
-7.641958544035237 -7.55218417450827
7.571196214035237 7.48142184450827
-7.5555416440352365 -7.465767274508269
6.286430664035236 6.196656294508268
-6.344883824035236 -6.255109454508268
6.031274924035237 5.941500554508269
-5.817313784035237 -5.72753941450827
2.0729065140352367 1.9831321445082692
-1.2315527640352366 -1.1417783945082691
1.9906924540352366 1.9009180845082692
-1.5577384740352367 -1.4679641045082692
0.2896274940352366 0.19985312450826906
-0.12880306403523667 -0.03902869450826914
-3.896710215964764 -3.9864845854917315
-0.17521647403523632 -0.08544210450826879
-0.9104722859647634 -1.000246655491731
0.5272869259647633 0.617061295491731
-0.4301065759647634 -0.5198809454917311
0.04092121596476339 0.1306955854917311
0.6163716940352367 0.526597324508269
-0.8690067240352366 -0.7792323545082689
-3.1655065559647637 -3.255280925491731
3.517569725964764 3.6073440954917313
-3.831178625964764 -3.920952995491731
2.703399135964764 2.793173505491731
-2.524626755964764 -2.6144011254917308
3.1483406659647644 3.238115035491731
-3.0155395659647644 -3.105313935491731
1.1089195759647645 1.198693945491731
-5.524584395964765 -5.6143587654917315
5.548457405964764 5.638231775491731
-4.801113665964763 -4.89088803549173
5.083944965964764 5.17371933549173
-4.901250685964764 -4.99102505549173
4.902913265964763 4.992687635491729
-9.465683895964762 -9.55545826549173
10.386380215964762 10.476154585491729
-11.128199255964761 -11.217973625491728
10.801125955964762 10.89090032549173
-15.109389545964762 -15.199163915491729
15.695187955964762 15.78496232549173
-17.53568101596476 -17.625455385491726
13.49575432596476 13.585528695491728
-16.09820708596476 -16.187981455491727
15.13670988596476 15.226484255491728
-16.94095771596476 -17.030732085491728
13.82380158596476 13.913575955491728
-12.99406836596476 -13.083842735491727
8.962555085964759 9.052329455491726
-8.554386665964758 -8.644161035491726
8.008128675964757 8.097903045491725
-7.055852435964757 -7.145626805491725
7.103093605964758 7.192867975491725
-10.850813325964758 -10.940587695491725
10.913709125964758 11.003483495491725
-11.32187869596476 -11.411653065491727
12.21100288596476 12.300777255491727
-11.456728925964761 -11.546503295491728
11.858937425964761 11.948711795491729
-12.808774175964762 -12.89854854549173
12.749458985964763 12.83923335549173
-12.837376255964763 -12.92715062549173
13.075774635964764 13.165549005491732
-14.338580965964766 -14.428355335491734
13.18864734596477 13.278421715491737
-12.47450152596477 -12.564275895491738
12.366224545964771 12.455998915491739
-13.639335525964771 -13.729109895491739
14.483514135964773 14.57328850549174
-14.450333785964773 -14.54010815549174
14.148101975964773 14.23787634549174
-15.706113265964774 -15.795887635491741
16.449457005964774 16.53923137549174
-17.87979524596477 -17.96956961549174
18.359907115964774 18.44968148549174
-18.60101602596477 -18.69079039549174
18.980149215964772 19.06992358549174
-18.964494645964773 -19.05426901549174
19.399443895964772 19.48921826549174
-18.442181645964776 -18.531956015491744
17.001836345964776 17.091610715491743
-16.255222615964772 -16.34499698549174
14.815877315964775 14.905651685491742
-14.324058915964775 -14.413833285491743
14.613358205964774 14.703132575491741
-18.658284895964776 -18.748059265491744
19.388957955964777 19.478732325491745
-22.569780695964777 -22.659555065491745
21.595410645964776 21.685185015491744
-23.530903705964775 -23.620678075491742
19.490247775964775 19.580022145491746
-23.660020105964772 -23.749794475491743
24.49538992596477 24.58516429549174
-26.36008901596477 -26.449863385491742
26.810340385964775 26.900114755491746
-26.276473835964772 -26.366248205491743
25.54537941596477 25.63515378549174
-26.27847383596477 -26.368248205491742
25.49366480596477 25.58343917549174
-27.02442130596477 -27.11419567549174
27.48267267596477 27.572447045491742
-29.36818508596477 -29.457959455491743
30.163730215964772 30.253504585491743
-31.503762245964772 -31.593536615491743
31.310964785964774 31.400739155491745
-31.06488515596477 -31.15465952549174
30.09874633596477 30.18852070549174
-31.046067525964766 -31.135841895491737
24.891815385964765 24.981589755491736
-24.35273231596477 -24.44250668549174
23.38231249596477 23.47208686549174
-22.64196875596477 -22.73174312549174
21.282243585964768 21.37201795549174
-21.22949973596477 -21.31927410549174
16.00443681596477 16.09421118549174
-16.225886105964765 -16.315660475491736
15.926529905964763 16.016304275491738
-15.747757525964762 -15.837531895491736
14.95894849596476 15.048722865491735
-16.002235795964758 -16.092010165491732
14.048149885964756 14.13792425549173
-13.806751505964755 -13.89652587549173
11.870258445964755 11.96003281549173
-11.466067025964756 -11.555841395491731
11.078881665964756 11.16865603549173
-12.512219905964756 -12.60199427549173
12.748257135964755 12.83803150549173
-12.595076785964753 -12.684851155491728
11.805267755964753 11.895042125491727
-11.978065495964751 -12.067839865491726
12.37527399596475 12.465048365491725
-12.36561942596475 -12.455393795491725
12.299283265964748 12.389057635491723
-11.846491125964748 -11.936265495491723
12.409972105964748 12.499746475491722
-12.308076305964747 -12.397850675491721
10.506828475964745 10.59660284549172
-10.243242335964746 -10.33301670549172
8.886806155964747 8.976580525491721
-8.576253595964747 -8.666027965491722
9.007207575964749 9.096981945491724
-10.470968575964749 -10.560742945491723
8.898948615964748 8.988722985491723
-8.560357975964749 -8.650132345491723
8.314849815964749 8.404624185491723
-7.574506075964748 -7.664280445491722
7.677401875964748 7.767176245491723
-7.363334375964748 -7.453108745491723
7.584732755964748 7.674507125491723
-7.826264345964749 -7.916038715491724
8.37575280596475 8.465527175491724
-8.224460905964749 -8.314235275491724
8.539051545964748 8.628825915491722
-8.13883344596475 -8.228607815491724
6.313126065964749 6.402900435491723
-7.060945105964748 -7.150719475491723
7.114755705964749 7.204530075491723
-11.157682395964748 -11.247456765491723
12.23967898596475 12.329453355491724
-12.09905286596475 -12.188827235491724
11.88907961596475 11.978853985491725
-13.840165525964752 -13.929939895491726
13.65527315596475 13.745047525491724
-14.90950167596475 -14.999276045491724
15.153900055964751 15.243674425491726
-15.208087465964752 -15.297861835491727
12.103217735964751 12.192992105491726
-11.85681935596475 -11.946593725491725
10.767130595964751 10.856904965491726
-12.174617255964753 -12.264391625491728
12.121615795964752 12.211390165491727
-11.314311405964753 -11.404085775491728
11.664374575964754 11.754148945491728
-11.733508955964753 -11.823283325491728
10.204784075964753 10.294558445491727
-9.750532705964755 -9.84030707549173
9.225520815964755 9.31529518549173
-8.662374995964756 -8.75214936549173
9.107679215964755 9.19745358549173
-13.297912885964756 -13.38768725549173
12.773810195964758 12.863584565491733
-12.860501485964758 -12.950275855491732
13.421148945964758 13.510923315491732
-14.937905445964756 -15.02767981549173
15.486929585964756 15.57670395549173
-14.930441125964757 -15.020215495491732
14.379899335964756 14.469673705491731
-15.546795675964757 -15.636570045491732
11.357562005964756 11.44733637549173
-12.322302045964754 -12.412076415491729
7.930625315964754 8.020399685491729
-8.078561665964754 -8.168336035491729
8.423624835964754 8.513399205491728
-8.765331835964753 -8.855106205491728
9.172627765964753 9.262402135491728
-10.917183985964755 -11.00695835549173
11.001182995964756 11.09095736549173
-10.172512385964756 -10.262286755491731
10.231256235964755 10.32103060549173
-10.294341185964754 -10.384115555491729
9.746083195964752 9.835857565491727
-9.007739455964751 -9.097513825491726
9.451167725964753 9.540942095491728
-12.318802225964754 -12.408576595491729
12.005193325964754 12.094967695491729
-13.513949825964755 -13.60372419549173
7.171830455964754 7.2616048254917285
-6.913704495964755 -7.003478865491729
7.258767665964755 7.34854203549173
-7.247113095964755 -7.3368874654917295
5.2787481059647545 5.368522475491729
-7.597815135964755 -7.687589505491729
5.6633220759647545 5.753096445491729
-6.929433055964755 -7.01920742549173
6.955306065964755 7.045080435491729
-7.0919650759647554 -7.18173944549173
7.524856005964756 7.61463037549173
-7.235556715964756 -7.32533108549173
4.754572855964756 4.844347225491731
-3.6411648559647567 -3.7309392254917313
4.445766285964757 4.535540655491731
-4.9705194059647555 -5.06029377549173
6.055296565964754 6.145070935491729
-5.744690605964754 -5.834464975491729
3.9281526259647546 4.017926995491729
-5.615659385964755 -5.70543375549173
4.009209295964755 4.098983665491731
-4.206284005964755 -4.2960583754917305
2.3950361759647545 2.48481054549173
-2.153637795964755 -2.2434121654917303
2.2537219559647546 2.34349632549173
-1.5004479959647545 -1.59022236549173
1.1982161859647549 1.2879905554917304
-1.1630358359647548 -1.2528102054917303
0.09398144596475487 0.18375581549173037
-1.5923026559647548 -1.6820770254917303
2.2535955659647553 2.343369935491731
-1.796644625964755 -1.8864189954917303
1.9754170059647551 2.06519137549173
-1.7520186259647554 -1.8417929954917305
2.4711817359647554 2.5609561054917305
-5.965550465964756 -6.055324835491731
6.022190455964757 6.111964825491731
-10.055703735964759 -10.145478105491733
11.027527565964759 11.117301935491733
-11.341136465964759 -11.430910835491733
9.57149188596476 9.661266255491734
-11.447512055964761 -11.537286425491736
12.406016855964763 12.495791225491738
-11.684018655964763 -11.773793025491738
9.778308025964762 9.868082395491736
-9.323363985964763 -9.413138355491737
8.796610865964764 8.886385235491739
-12.634939965964762 -12.724714335491736
12.606189685964763 12.695964055491737
-13.181994555964762 -13.271768925491736
12.419775015964763 12.509549385491738
-13.918096225964764 -14.007870595491738
13.846760065964762 13.936534435491737
-13.689722835964762 -13.779497205491737
11.762574875964763 11.852349245491737
-11.851266165964761 -11.941040535491735
12.770028525964761 12.859802895491736
-12.523630145964761 -12.613404515491736
13.094606995964762 13.184381365491737
-12.875934635964763 -12.965709005491737
10.390950775964761 10.480725145491736
-12.20981534596476 -12.299589715491734
8.13688865596476 8.226663025491735
-7.39954491596476 -7.489319285491734
7.76832287596476 7.858097245491734
-7.420259705964759 -7.510034075491734
8.166603445964759 8.256377815491733

In [22]:
dataset['cluster belonges'] = answer

In [23]:
## if you look we can now see which data points belongs to which clusters with the clumnname cluster belongs 
dataset

        X1        X2   X3        X4        X5  cluster belonges
0    0.320  0.084879  1.0  0.249830  0.121540                 2
1    0.195  0.306595  0.9  0.249803  0.121540                 1
2    0.133  0.561984  0.5  0.249875  0.121544                 2
3    0.133  0.561984  0.5  0.249875  0.121544                 1
4    0.050  0.390568  0.5  0.249794  0.121542                 2
5    0.071  2.175030  0.3  0.249630  0.121513                 1
6    0.345  0.623473  0.7  0.249793  0.121536                 2
7    0.203  0.287603  0.6  0.249804  0.121542                 1
8    0.317  5.512038  0.1  0.249509  0.121485                 2
9    0.179  1.783180  0.3  0.249673  0.121515                 1
10   0.348  0.405213  0.1  0.249735  0.121534                 2
11   0.063  0.090456  0.9  0.249743  0.121543                 1
12   0.130  0.492231  0.5  0.249652  0.121537                 2
13   0.204  2.469645  0.4  0.249611  0.121510                 1
14   0.132  1.164838  0.4  0.249916  0.121534                 2
15   0.357  0.579208  0.2  0.249824  0.121546                 1
16   0.000  0.292998  0.6  0.249774  0.121545                 2
17   0.177  0.350851  0.1  0.249754  0.121531                 1
18   0.169  0.368136  0.8  0.249675  0.121545                 2
19   0.015  0.023383  0.7  0.249677  0.121541                 1
20   0.045  2.275877  0.3  0.249631  0.121512                 2
21   0.105  0.279173  0.7  0.249753  0.121545                 1
22   0.147  1.360139  0.1  0.249520  0.121548                 2
23   0.101  0.279173  0.7  0.249753  0.121545                 1
24   0.396  0.480698  0.4  0.249735  0.121539                 2
25   0.293  1.487868  0.2  0.249754  0.121517                 1
26   0.031  0.383862  0.5  0.249808  0.121544                 2
27   0.104  0.276449  0.5  0.249559  0.121539                 1
28   0.192  0.557478  0.4  0.249742  0.121538                 2
29   0.071  0.451244  0.5  0.249756  0.121547                 1
..     ...       ...  ...       ...       ...               ...
384  0.161  4.066587  0.0  0.249430  0.121503                 2
385  0.183  0.082886  1.0  0.249830  0.121540                 1
386  0.000  0.185430  0.0  0.249711  0.121532                 2
387  0.162  2.103555  0.3  0.249604  0.121515                 1
388  0.104  2.251938  0.4  0.249596  0.121514                 2
389  0.409  0.122362  0.8  0.249676  0.121542                 1
390  0.328  0.377830  0.9  0.249715  0.121543                 2
391  0.062  1.939749  0.1  0.249516  0.121554                 1
392  0.427  0.443802  0.6  0.249793  0.121539                 2
393  0.169  0.967400  0.4  0.249887  0.121534                 1
394  0.326  4.136271  0.1  0.249554  0.121496                 2
395  0.212  0.512549  0.4  0.249740  0.121538                 1
396  0.371  0.918636  0.1  0.249720  0.121551                 2
397  0.131  1.164838  0.4  0.249916  0.121534                 1
398  0.147  1.717193  0.2  0.249645  0.121516                 2
399  0.127  0.170129  0.1  0.249737  0.121530                 1
400  0.268  0.482758  0.5  0.249743  0.121539                 2
401  0.076  2.175030  0.3  0.249630  0.121513                 1
402  0.127  0.187482  0.1  0.249739  0.121530                 2
403  0.309  0.161942  0.9  0.249835  0.121540                 1
404  0.164  0.289325  0.5  0.249820  0.121543                 2
405  0.230  0.130994  0.6  0.249566  0.121538                 1
406  0.019  0.372139  0.7  0.249729  0.121540                 2
407  0.052  2.408993  0.0  0.249551  0.121560                 1
408  0.185  2.175744  0.3  0.249633  0.121512                 2
409  0.137  4.082015  0.0  0.249415  0.121504                 1
410  0.056  0.090456  0.9  0.249743  0.121543                 2
411  0.188  0.390970  0.7  0.249792  0.121540                 1
412  0.081  0.104810  0.5  0.249667  0.121541                 2
413  0.065  0.090456  0.9  0.249743  0.121543                 1

[414 rows x 6 columns]